# Generated by Django 5.1 on 2024-09-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='nationality',
            new_name='middle_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='passport_number',
        ),
    ]
